---
swagger: "2.0"
info:
  version: "2016-03-07T21:52:55Z"
  title: "addon-test"
host: "nl1fctyzr7.execute-api.us-east-1.amazonaws.com"
basePath: "/staging"
schemes:
- "https"
paths:
  /addon:
    get:
      consumes:
      - "application/json"
      parameters:
      - name: "ember_version"
        in: "query"
        required: false
        type: "string"
      - name: "addon_version"
        in: "query"
        required: false
        type: "string"
      - name: "addon"
        in: "query"
        required: false
        type: "string"
      responses:
        301:
          description: "301 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Location:
              type: "string"
        404:
          description: "404 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
    head:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
definitions:
  Empty:
    type: "object"
